//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PService
{
    using System;
    using System.Collections.Generic;
    
    public partial class debt_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public debt_table()
        {
            this.active_debts = new HashSet<active_debts>();
        }
    
        public int id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> service_id { get; set; }
        public Nullable<int> month_id { get; set; }
        public Nullable<decimal> debt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<active_debts> active_debts { get; set; }
        public virtual clients_table clients_table { get; set; }
        public virtual months_2020_table months_2020_table { get; set; }
        public virtual service_type service_type { get; set; }
    }
}
