//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PSEntity : DbContext
    {
        public PSEntity()
            : base("name=PSEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<active_debts> active_debts { get; set; }
        public virtual DbSet<client_acc_table> client_acc_table { get; set; }
        public virtual DbSet<clients_table> clients_table { get; set; }
        public virtual DbSet<debt_table> debt_table { get; set; }
        public virtual DbSet<metrics_archive> metrics_archive { get; set; }
        public virtual DbSet<months_2020_table> months_2020_table { get; set; }
        public virtual DbSet<service_metrcis> service_metrcis { get; set; }
        public virtual DbSet<service_payments> service_payments { get; set; }
        public virtual DbSet<service_type> service_type { get; set; }
        public virtual DbSet<service_usage> service_usage { get; set; }
        public virtual DbSet<staff_acc_table> staff_acc_table { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<virtual_money> virtual_money { get; set; }
        public virtual DbSet<worker_table> worker_table { get; set; }
    }
}
