//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PService
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_usage
    {
        public int id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<bool> service_1 { get; set; }
        public Nullable<bool> service_2 { get; set; }
        public Nullable<bool> service_3 { get; set; }
        public Nullable<bool> service_4 { get; set; }
        public Nullable<bool> service_5 { get; set; }
        public Nullable<bool> service_6 { get; set; }
        public Nullable<bool> service_7 { get; set; }
    
        public virtual clients_table clients_table { get; set; }
    }
}
