//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PService
{
    using System;
    using System.Collections.Generic;
    
    public partial class worker_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public worker_table()
        {
            this.staff_acc_table = new HashSet<staff_acc_table>();
        }
    
        public int worker_id { get; set; }
        public string name { get; set; }
        public Nullable<int> phone_number { get; set; }
        public string street { get; set; }
        public string flat { get; set; }
        public string house { get; set; }
        public string job { get; set; }
        public Nullable<double> wage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<staff_acc_table> staff_acc_table { get; set; }
    }
}
